merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band_list'),
    path('bands/<int:band_id>/', views.band_detail, name='band_detail'),
    path('contact-us/', views.contact, name='contact'),
    path('about-us/', views.about, name='about'),
    path('listing/', views.listing, name='listing'),
    path('email-sent/', views.received, name='email-sent')
]

merchex/listings/models.py
"""
- name (CharField) : Nom du groupe.
    - description (CharField) : Description courte du groupe.
    - biography (CharField) : Biographie détaillée du groupe.
    - genre (CharField) : Genre musical, choisi parmi une liste
    prédéfinie (Genre).
    - year_formed (IntegerField) : Année de formation du groupe,
    entre 1300 et 2021.
    - active (BooleanField) : Indique si le groupe est toujours actif.
    - official_homepage (URLField) : URL officielle du groupe (optionnel).
    - sold (BooleanField) : Indique si le produit est vendu.
    - type (CharField) : Type de produit associé, parmi
    une liste prédéfinie (Type).
    - like_new (BooleanField) : Indique si l'objet est en état "comme neuf".
    """
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Band(models.Model):
    """Création des champs de la table band """
    class Genre(models.TextChoices):
        """Missing"""
        ALTERNATIVE_ROCK = 'AR'
        BLUES = 'BL'
        CLASSICAL = 'CL'
        HIP_HOP = 'HH'
        HARD_ROCK = 'HR'
        REGGAE = 'RG'
        SYNTH_POP = 'SP'

    class Type(models.TextChoices):
        """Missing"""
        DISQUES = 'Records'
        VETEMENTS = "Clothing"
        AFFICHES = 'Posters'
        DIVERS = 'Miscellaneous'

    name = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=100)
    # default="Sans titre"
    biography = models.fields.CharField(max_length=1000)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    # ou un choix, par exemple
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1300), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    sold = models.fields.BooleanField(default=False)
    type = models.fields.CharField(choices=Type.choices, max_length=15)
    like_new = models.fields.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'


class Listing(models.Model):
    """Missing"""
    title = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return f'{self.title}'

    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
"""listings/forms.py"""

from django import forms


class ContactUsForm(forms.Form):
    """Parametre du formulaire forms"""
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

merchex/listings/views.py
"""Missing"""
from listings.models import Band
from listings.models import Listing
from listings.forms import ContactUsForm
# from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect  # ajoutez cet import
from django.core.mail import send_mail


def band_list(request):
    """Missing"""
    bands = Band.objects.all()
    return render(
        request,
        'listings/band_list.html',
        {'bands': bands})


def about(request):
    """ Affiche Nous adorons merch sur la page web"""
    return render(request, 'listings/about.html')


def listing(request):
    """Missing"""
    listing_data = Listing.objects.all()
    return render(request, 'listings/listing.html', {'listing': listing_data})


def contact(request):
    """Missing"""
    # ajoutez ces instructions d'impression afin que nous
    # puissions jeter un coup d'oeil à « request.method »
    # et à « request.POST »
    # ...nous pouvons supprimer les déclarations de
    # journalisation qui étaient ici...

    if request.method == 'POST':
        # créer une instance de notre formulaire et le remplir
        # avec les données POST
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
                )
    # si le formulaire n'est pas valide, nous laissons l'exécution continuer jusqu'au return
    # ci-dessous et afficher à nouveau le formulaire (avec des erreurs).
        return redirect('email-sent')  # ajoutez cette instruction de retour
    else:
        # ceci doit être une requête GET, donc créer un formulaire vide
        form = ContactUsForm()  # ajout d’un nouveau formulaire ici
    return render(
        request,
        'listings/contact.html',
        {'form': form})  # passe ce formulaire au gabarit)


def band_detail(request, band_id):  # notez le paramètre id supplémentaire
    """Missing"""
    band = Band.objects.get(id=band_id)  # on utilise band_id ici
    return render(
        request,
        'listings/band_detail.html',
        {'band': band})  # nous passons l'id au modèle


def received(request):
    """Affiche une page confirmant l'envoi de l'email"""
    return render(request, 'listings/email_sent.html')

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}
  <h1>À propos</h1>
  <p>Bienvenue sur Merchex, la plateforme de vente musicale !</p>
{% endblock %}

merchex/listings/templates/listings/band_detail.html
# listings/templates/listings/band_detail.html

{% extends 'listings/base.html' %}
{% block content %}
<h2>{{ band.name }}</h2>
<ul>
<li>Genre : {{ band.get_genre_display }}</li>
<li>Année de formation : {{ band.year_formed }}</li>
<li>Actif : {{ band.active|yesno }}</li>
{% if band.official_homepage %}
<li>Site officiel : <a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
{% endif %}
</ul>
<p>Biographie : {{ band.biography }}</p>
<a href="{% url 'band_list' %}">Retour à tous les groupes</a>
{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}
{% block content %}
<h1>Groupes !</h1>

<ul>

    {% for band in bands %}
        <li><a href="{% url 'band_detail' band.id %}">{{ band.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8" />
    <title>Merchex</title>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
</head>
<body>
    <nav>
        <ul>
            <li>
                <a href="{% url 'band_list' %}"
                class="{% if request.resolver_match.url_name == 'band_list' %}active{% endif %}">
                    Groupes  </a>
            </li>
            <li>
                <a href="{% url 'listing' %}"
                class="{% if request.resolver_match.url_name == 'listing' %}active{% endif %}">
                    Annonces
                </a>
            </li>
            <li>
                <a href="{% url 'contact' %}"
                class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
        Contact
    </a>
            </li>
            <li>
                <a href="{% url 'about' %}"
                class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}">
                    À propos
                </a>
            </li>
        </ul>
    </nav>
    <main>
    {% block content %}
    {% endblock %}
    </main>
</body>
</html>

merchex/listings/templates/listings/contact.html
<!-- En résumé :
Ce template HTML :
est utilisé dans un projet Django.
affiche un formulaire de contact généré dynamiquement par Django.
utilise une méthode sécurisée (POST + CSRF).
présente le formulaire en format simple et lisible (as_p). -->
<!DOCTYPE html>  <!--indique que le document est en HTML5 -->
{% extends 'listings/base.html' %}
{% block content %}
<h1>Contact</h1>
<p>Nous sommes là pour vous aider.</p>
<body>
<form action="" method="post" novalidate>  
<!--action="" : envoie les données à la même URL que la page actuelle. -->
<!-- novalidate : désactive la validation HTML5 automatique (pour laisser Django valider).-->
{% csrf_token %}  
<!-- {% csrf_token %}  balise Django qui insère un jeton de 
    sécurité contre les attaques CSRF. Obligatoire dans 
    les formulaires POST.-->
{{ form.as_p }}
<!--{{ form.as_p }} : affiche le formulaire 
    Django (généré dans la vue Python) 
    sous forme de paragraphes-->

<input type="submit" value="Envoyer"> 
<!--<input type="submit" value="Envoyer"> : bouton pour envoyer le formulaire.-->
</form>
{% endblock %}

merchex/listings/templates/listings/email_sent.html
<!-- templates/listings/email_sent.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Email envoyé</title>
</head>
<body>
    <h1>Merci !</h1>
    <p>Votre message a bien été envoyé. Nous vous répondrons dès que possible.</p>
    <a href="{% url 'contact' %}">Retour au formulaire de contact</a>
</body>
</html>

merchex/listings/templates/listings/forms.html
"""listings/forms.py"""

from django import forms


class ContactUsForm(forms.Form):
    """Parametre du formulaire forms"""
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

merchex/listings/templates/listings/helloancien.html
# listings/templates/listings/hello.html

<p>Mes groupes préférés sont :</p>
<p>J'ai {{ bands|length }} groupes préférés.</p>
<p>
    J'ai..
    {% if bands|length < 5 %}
        peu de
    {% elif bands|length < 10 %}
        quelques
    {% else %}
        beaucoup de
    {% endif %}
        groupes préférés.
</p>
<ul>
    {% for band in bands %}
    <li>{{ band.name |upper  }}<li>
        
    {% endfor %}
<ul>

merchex/listings/templates/listings/listing.html
<!-- listings/templates/listings/listing.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Liste des annonces</title>
</head>
<body>
    <h1>Liste des annonces</h1>

    {% if listing %}
        <ul>
        {% for listing in listing %}
            <li>
                <strong>{{ listing.title }}</strong><br>
                {{ listing.description }}
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Aucune annonce pour le moment.</p>
    {% endif %}
</body>
</html>